# Generated by Django 5.2.8 on 2025-11-29 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Category image/')),
                ('desc', models.TextField()),
                ('view', models.PositiveBigIntegerField()),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('brown', 'Brown'), ('gray', 'Gray'), ('gold', 'Gold'), ('silver', 'Silver')], default='black', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('desc', models.TextField()),
                ('main_image', models.FileField(upload_to='images_main/')),
                ('price', models.IntegerField()),
                ('quantity', models.BigIntegerField(default=0)),
                ('year', models.SmallIntegerField(default=2025)),
                ('delivery_time', models.CharField(choices=[('3_days', '1–3 days'), ('5_days', '3–5 days'), ('1_week', '5–7 days'), ('2_weeks', '1–2 weeks'), ('1_month', '2–4 weeks')], default='3_days', max_length=100)),
                ('review', models.TextField()),
                ('rate', models.SmallIntegerField(default=2)),
                ('company', models.CharField(max_length=150)),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('lenovo', 'Lenovo'), ('huawei', 'Huawei'), ('asus', 'ASUS'), ('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('zara', 'Zara'), ('hm', 'H&M'), ('sony', 'Sony'), ('lg', 'LG'), ('gucci', 'Gucci'), ('prada', 'Prada'), ('tesla', 'Tesla')], default='gucci', max_length=50)),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', '3XL'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], default='xs', max_length=500)),
                ('discount', models.SmallIntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('condition', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.countrymodel')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='detailed_image_of_product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
            ],
        ),
    ]
